# permissions for end users to edit xilinxtestoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xilinxtestoperator-editor-role
rules:
- apiGroups:
  - xilinxtestoperators.test.cablelabs.com
  resources:
  - xilinxtestoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xilinxtestoperators.test.cablelabs.com
  resources:
  - xilinxtestoperators/status
  verbs:
  - get
