# permissions for end users to view xilinxtestoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xilinxtestoperator-viewer-role
rules:
- apiGroups:
  - xilinxtestoperators.test.cablelabs.com
  resources:
  - xilinxtestoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xilinxtestoperators.test.cablelabs.com
  resources:
  - xilinxtestoperators/status
  verbs:
  - get
